admissionwebhook:
  type: ClusterIP
autoGenerateCert: true
bootstrapPassword: ''
bottlerocket:
  enabled: false
  runtimePath: /run/dockershim.sock
containerd:
  enabled: false
  path: /var/run/containerd/containerd.sock
controller:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - neuvector-controller-pod
            topologyKey: kubernetes.io/hostname
          weight: 100
  annotations: {}
  apisvc:
    annotations: {}
    nodePort: null
    route:
      enabled: false
      host: null
      termination: passthrough
      tls: null
    type: null
  azureFileShare:
    enabled: false
    secretName: null
    shareName: null
  certificate:
    keyFile: tls.key
    pemFile: tls.pem
    secret: ''
  certupgrader:
    env: []
    imagePullPolicy: IfNotPresent
    nodeSelector: {}
    podAnnotations: {}
    podLabels: {}
    priorityClassName: null
    runAsUser: null
    schedule: ''
    timeout: 3600
    tolerations: []
  configmap:
    data: null
    enabled: false
  disruptionbudget: 0
  enabled: true
  env: []
  federation:
    managedsvc:
      annotations: {}
      clusterIP: null
      externalTrafficPolicy: null
      ingress:
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        enabled: false
        host: null
        ingressClassName: ''
        path: /
        secretName: null
        tls: false
      internalTrafficPolicy: null
      loadBalancerIP: null
      nodePort: null
      route:
        enabled: false
        host: null
        termination: passthrough
        tls: null
      type: null
    mastersvc:
      annotations: {}
      clusterIP: null
      externalTrafficPolicy: null
      ingress:
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        enabled: false
        host: null
        ingressClassName: ''
        path: /
        secretName: null
        tls: false
      internalTrafficPolicy: null
      loadBalancerIP: null
      nodePort: null
      route:
        enabled: false
        host: null
        termination: passthrough
        tls: null
      type: null
  image:
    hash: null
    imagePullPolicy: IfNotPresent
    repository: rancher/neuvector-controller
    tag: 5.4.5
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    enabled: true
    host: nvc01.bulletproof-labs.com
    ingressClassName: ''
    path: /
    secretName: null
    tls: false
  internal:
    certificate:
      caFile: ca.crt
      keyFile: tls.key
      pemFile: tls.crt
      secret: ''
  nodeSelector: {}
  podAnnotations: {}
  podLabels: {}
  prime:
    enabled: true
    image:
      hash: null
      imagePullPolicy: IfNotPresent
      repository: rancher/neuvector-compliance-config
      tag: 1.0.6
  priorityClassName: null
  pvc:
    accessModes:
      - ReadWriteMany
    capacity: null
    enabled: false
    existingClaim: false
    storageClass: null
  ranchersso:
    enabled: true
  replicas: 3
  resources: {}
  schedulerName: null
  searchRegistries: null
  secret:
    data:
      userinitcfg.yaml:
        users:
          - Fullname: admin
            Password: null
            Role: admin
    enabled: false
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  tolerations: []
  topologySpreadConstraints: []
crdwebhook:
  enabled: true
  type: ClusterIP
crdwebhooksvc:
  enabled: true
crio:
  enabled: false
  path: /var/run/crio/crio.sock
cve:
  adapter:
    affinity: {}
    certificate:
      keyFile: tls.key
      pemFile: tls.crt
      secret: ''
    enabled: false
    env: []
    harbor:
      protocol: https
      secretName: null
    image:
      hash: null
      imagePullPolicy: IfNotPresent
      repository: rancher/neuvector-registry-adapter
      tag: 0.1.8
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      enabled: false
      host: null
      ingressClassName: ''
      path: /
      secretName: null
      tls: false
    internal:
      certificate:
        caFile: ca.crt
        keyFile: tls.key
        pemFile: tls.crt
        secret: ''
    nodeSelector: {}
    podAnnotations: {}
    podLabels: {}
    priorityClassName: null
    resources: {}
    route:
      enabled: true
      host: null
      termination: passthrough
      tls: null
    runAsUser: null
    svc:
      annotations: {}
      loadBalancerIP: null
      type: ClusterIP
    tolerations: []
  scanner:
    affinity: {}
    dockerPath: ''
    enabled: true
    env: []
    image:
      hash: null
      imagePullPolicy: Always
      registry: ''
      repository: rancher/neuvector-scanner
      tag: '6'
    internal:
      certificate:
        caFile: ca.crt
        keyFile: tls.key
        pemFile: tls.crt
        secret: ''
    nodeSelector: {}
    podAnnotations: {}
    podLabels: {}
    priorityClassName: null
    replicas: 3
    resources: {}
    runAsUser: null
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      type: RollingUpdate
    tolerations: []
    topologySpreadConstraints: []
    volumeMounts: null
    volumes: null
  updater:
    cacert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    enabled: true
    image:
      hash: null
      imagePullPolicy: IfNotPresent
      registry: ''
      repository: rancher/neuvector-updater
      tag: 0.0.4
    nodeSelector: {}
    podAnnotations: {}
    podLabels: {}
    priorityClassName: null
    resources: {}
    runAsUser: null
    schedule: 0 0 * * *
    secure: false
    tolerations: []
defaultValidityPeriod: 365
docker:
  path: /var/run/docker.sock
enforcer:
  enabled: true
  env: []
  image:
    hash: null
    imagePullPolicy: IfNotPresent
    repository: rancher/neuvector-enforcer
    tag: 5.4.5
  internal:
    certificate:
      caFile: ca.crt
      keyFile: tls.key
      pemFile: tls.crt
      secret: ''
  podAnnotations: {}
  podLabels: {}
  priorityClassName: null
  resources: {}
  securityContext:
    privileged: true
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
    - effect: NoSchedule
      key: node-role.kubernetes.io/etcd
  updateStrategy:
    type: RollingUpdate
global: # required for rancher authentication (https://<Rancher_URL>/)
  cattle:
    psp:
      enabled: false
    url: https://rancher.bulletproof-labs.com
  azure:
    enabled: false
    identity:
      clientId: "DONOTMODIFY" # Azure populates this value at deployment time
    marketplace:
      planId: "DONOTMODIFY" # Azure populates this value at deployment time
    extension:
      resourceId: "DONOTMODIFY" # application's Azure Resource ID, Azure populates this value at deployment time
    serviceAccount: csp
    imagePullSecrets:
    images:
      neuvector_csp_pod:
        tag: latest
        image: neuvector-billing-azure-by-suse-llc
        registry: registry.suse.de/suse/sle-15-sp5/update/pubclouds/images
        imagePullPolicy: IfNotPresent
      controller:
        tag: 5.2.4
        image: controller
        registry: docker.io/neuvector
      manager:
        tag: 5.2.4
        image: manager
        registry: docker.io/neuvector
      enforcer:
        tag: 5.2.4
        image: enforcer
        registry: docker.io/neuvector

  aws:
    enabled: false
    accountNumber: ""
    roleName: ""
    serviceAccount: csp
    annotations: {}
    imagePullSecrets:
    image:
      digest: ""
      repository: neuvector/neuvector-csp-adapter
      tag: latest
      imagePullPolicy: IfNotPresent

internal:
  autoGenerateCert: true
  autoRotateCert: true
  certmanager:
    enabled: false
    secretname: neuvector-internal
k3s:
  enabled: false
  runtimePath: /run/k3s/containerd/containerd.sock
lease:
  enabled: true
leastPrivilege: false
manager:
  affinity: {}
  certificate:
    keyFile: tls.key
    pemFile: tls.pem
    secret: ''
  enabled: true
  env:
    envs: []
    ssl: true
  image:
    hash: null
    imagePullPolicy: IfNotPresent
    repository: rancher/neuvector-manager
    tag: 5.4.5
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    enabled: true
    host: nvm01.bulletproof-labs.com
    ingressClassName: ''
    path: /
    secretName: null
    tls: false
  nodeSelector: {}
  podAnnotations: {}
  podLabels: {}
  priorityClassName: null
  probes:
    enabled: false
    periodSeconds: 10
    startupFailureThreshold: 30
    timeout: 1
  resources: {}
  route:
    enabled: true
    host: null
    termination: passthrough
    tls: null
  runAsUser: null
  svc:
    annotations: {}
    loadBalancerIP: null
    nodePort: null
    type: ClusterIP
  tolerations: []
  topologySpreadConstraints: []
oem: null
openshift: false
rbac: true
registry: docker.io
resources: {}
runtimePath: null
serviceAccount: neuvector
tag: 5.4.5
